config/routes.rb
Rails.application.routes.draw do
  get '/', to:'posts#top', as: :top
  get '/registration', to:'users#registration', as: :registration
  post '/registration', to:'users#registration_process'
  get '/login', to:'users#login', as: :login
  post '/login', to:'users#login_process'
  get '/upload', to:'posts#upload', as: :upload
  resources :posts
  post '/upload', to:'posts#create', as: :create
  get '/manage/illusts', to:'posts#manage', as: :manage
  get '/artworks/{:id}', to:'posts#artworks'
  get '/users/{:id}/follow', to:'users#follow_list', as: :follow_list
  get '/users/{:id}/follower', to:'users#follower_list', as: :follower_list
  get '/users/bookmarks', to:'users#bookmarks'
  get '/users/profiles', to:'users#profiles', as: :profiles
  get '/setting_profile', to:'users#edit', as: :edit
  post '/setting_profile', to:'users#update', as: :update
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # before_action :authorize
  
  def top
    @posts = Post.all
    @posts = @posts.order("id desc")
    # @user = User.find(params[:id])
    @user = User.find(current_user.id)
    @reccomends = Post.where.not(id: current_user.id).limit(5)
  end
  
  def upload
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
  end
  
  def artworks
    @post =Post.find(params[:id])
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :comment, images: []).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # before_action :authorize
  
  def registration
    @user = User.new
  end
  
  def registration_process
    user = User.new(user_params)
    if user.save
      flash[:success] = "ユーザー登録に成功しました。"
      redirect_to("/login")
    else
      flash[:danger] = "ユーザー登録に失敗しました。"
      redirect_to("/registration")
    end
  end
  
  def login
    @user = User.new
  end
  
  def login_process
    password_md5 = User.generate_password(user_params[:password])
    user = User.find_by(email: user_params[:email], password: password_md5)
    
    if user
      user_login(user)
      flash[:success] = "ログインしました"
      redirect_to("/") and return
    else
      flash[:danger] = "ログインに失敗しました"
      redirect_to("/login")
    end
  end
  
  def profiles
    @user = User.find(current_user.id)
    @posts = Post.where(user_id: @user.id)
    @follows = Follow.where(user_id: @user.id)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(current_user.id)
    
    @user.name = params[:name]
    @user.comment =params[:comment]
    upload_file = params[:user][:image]
    if upload_file.present?
      upload_file_name = upload_file.original_filename
      output_dir = Rails.root.join('public', 'users')
      output_path = output_dir + upload_file_name
      
      File.open(output_path, 'w+b') do |f|
      f.write(upload_file.read)
    end
    current_user.update(user_params.merge({image: upload_file.original_filename}))
    end
    
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to("/users/{:id}")
    else
      flash[:danger] = "プロフィール更新に失敗しました。"
      redirect_to("/setting_profile")
    end
  end
  
  def follow
    @user = User.find(params[:id])
    if Follow.exists?(user_id: current_user.id, follow_user_id: @user.id)
      Follow.find_by(user_id: current_user.id, follow_user_id: @user.id).destroy
    else
      Follow.create(user_id: current_user.id, follow_user_id: @user.id)
    end
  end
  
  def follower
  end
  
  def follow_list
    @user = User.find(current_user.id)
    @users = User.where(id: Follow.where(user_id: @user.id).pluck(:follow_user_id))
  end
  
  def follower_list
    @user = User.find(current_user.id)
    @users = User.where(id: Follow.where(user_id: @user.id).pluck(:user_id))
  end
  
  def bookmarks
    @user = User.find(current_user.id)
    @postlikes = PostLike.where(user_id: @user.id)
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :comment, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Illustration</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="logined">
    <header class="global_header">
      <div class="icon">
        <%= link_to top_path do %>
          <h1 class="logo">illustration</h1>
        <% end %>
      </div>
      <form class="search">
        <input type="text" placeholder="検索" name="word" value="">
      </form>
      <ul class="menu">
        <li>
          <%= link_to profiles_path do %>  
          <i class="fa fa-user-o"></i>
          <% end %>
        </li>
        <li>
          <%= link_to upload_path do %>
            <i class="fa fa-upload"></i>
          <% end %>
        </li>
      </ul>
    </header>
    <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").slideUp();
        }, 3000);
    </script>
  </body>
</html>

app/views/posts/artworks.html.erb
<div class="container">
  <div class="posts">
    <ul>
      <li>
        <p><%= user.name %></p>
        <p><%= post.title %></p>
        <p><%= post.comment %></p>
        <div class="image">
          <!--画像は複数、どうする？-->
          <%= image_tag image1_url(@post) %>
        </div>
        <!--複数だったらすべて見る-->
      </li>
    </ul>
    <h3>コメントする</h3>
  </div>
  <div class="user">
    <div class="image">
      <%= link_to profiles_path do(user.id) %>
        <%= image_tag user_url(user) %>
        <%= user.name %>
      <% end %>
    </div>
    <p>フォローする</p>
  </div>
</div>

app/views/posts/top.html.erb
<div class="container">
  <div class="user">
    <ul>
      <div class="image">
        <%= link_to profiles_path do %>
        <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
        <%= @user.name %>
        <% end %>
      </div>
      <li>
        <%= link_to 'フォロー', '/users/{:id}/follow' %>
      </li>
      <li>
        <%= link_to 'フォロワー', '/users/{:id}/follower' %>
      </li>
      <li>
        <%= link_to 'ブックマーク', '/users/bookmarks' %>
      </li>
      <!--<li>閲覧履歴</li>-->
    </ul>
  </div>
  
  <% if @posts.any? %>
    <div class ="post">
      <ul>
        <% @posts.each do |post| %>
            <li>
              <div class ="image">
                <%= link_to artworks_path do %>
                  <%= image_tag image1_url(post) %>
                <% end %>
              </div>
              <p><%= product.title %></p>
              <p><%= user.name %></p>
            </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <p class="empty">投稿がありません。</p>
  <% end %>
  
  <% if @reccomends.any? %>
    <div class ="recommend">
    <h2>みんなの新着投稿</h2>
      <ul>
        <% @reccomends.each do |user| %>
          <li>
            <div class ="image">
              <%= link_to artworks_path do %>
                <%= image_tag image1_url(post) %>
              <% end %>
            </div>
            <p><%= post.name %></p>
            <p><%= @user.name %></p>
          </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <p class="empty">おすすめはありません。</p>
  <% end %>
</div>

app/views/posts/upload.html.erb
<div class="container">
  <div class="posts">
    <ul class ="upload_form">
    <%= form_for @post do |f| %>
      <div class="file_wrap">
        <!--複数投稿できるようにする-->
        <p>写真選択</p>
        <%= f.file_field :images, mutiple: true %>
      </div>
      <div class="field">
        <p>タイトル</p>
        <%= f.text_area :title %>
      </div>
      <div class="textarea_wrap">
        <p>キャプション</p>
        <%= f.text_area :caption %>
      </div>
      <!--タグ付け調べる-->
      <div class="textarea_wrap">
        <p>タグ</p>
        <%= f.text_area :tag %>
      </div>
    </ul>
    <div class="btn_wrap">
      <%= f.submit "送信する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/upload_novel.html.erb
<div class="container">
  <div class="posts">
    <ul class ="upload_novel_form">
      <div class="field">
        <%= f.text_area :title, "タイトル" %>
      </div>
      <div class="textarea_wrap">
        <%= f.text_area :caption, "キャプション" %>
      </div>
      <div class="textarea_wrap">
        <%= f.text_area :sentence, "本文" %>
      </div>
      <div class="textarea_wrap">
        <%= f.text_area :tag, "タグ" %>
      </div>
      <div class="file_wrap">
        <li><%= f.label :image, "表紙" %></li>
        <%= f.file_field :image, "ファイルを選択" %>
      </div>
    </ul>
  </div>
</div>

app/views/users/login.html.erb
<div class = "login">
  <div class = "login_form">
    <h1>イラスト投稿サイト</h1>
      <%= form_for @user, url: login_path do |f| %>
        <div class = "field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class = "field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>ログイン</button>
      <% end %>
    <div class = "registration_link">
      <p><%= link_to registration_path do %>新規登録<% end %></p>
    </div>
  </div>
</div>

app/views/users/registration.html.erb
<div class = "registration">
  <div class = "registration_form">
    <h1>イラスト投稿サイト</h1>
    <h1>アカウント作成</h1>
      <%= form_for @user, url: registration_path do |f| %>
        <div class = "field">
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class = "field">
          <%= f.password_field :password, placeholder: "パスワード" %>
        </div>
        <button>登録する</button>
      <% end %>
    <div class = "login_link">
      <p><%= link_to login_path do %>ログイン<% end %></p>
    </div>
  </div>
</div>